# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a65283c6c6eeee93f532f5b0c0b65024069107b75c677cd30bda00e17b4944f13054f7c86a050e8cbe68c699618eb8c022686ae226231dfd0d4d0187edfa301

test:
  secret_key_base: c5c001f0672f21e5569f04dc51b031b98b6c305f857b49f9a279174d4db760e456ff7199eab02a0d1ab3783f46da36e473d525deb6056654c754467c9907d9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
